import { chromium } from 'playwright';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
if (existsSync("../data/audit-skills/run.json")) throw Error("研究已创建，请使用已有任务，避免重复采集和模型调用");
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1366,height:768}});
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8000/research');
await page.getByRole('button',{name:'新建研究'}).click();
await page.getByLabel('研究名称').fill('好用的 Agent Skills：真实用途与选择建议');
await page.locator('.ant-modal .ant-select-selection-item-remove').click();
const keywords=page.getByLabel('关键词');
await keywords.fill('Claude Skills'); await keywords.press('Enter');
await keywords.fill('Agent Skills'); await keywords.press('Enter');
await page.getByLabel('目标读者').fill('想找到实用 Agent Skills 的个人创作者与开发者，关注具体用途、安装成本、适用场景和真实经验');
await page.getByLabel('时间范围').click();
await page.getByText('最近 30 天',{exact:true}).click();
await page.getByLabel('采样上限').fill('6');
const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/v1/research-runs') && r.request().method()==='POST');
await page.getByRole('button',{name:'开始研究',exact:true}).click();
const response=await responsePromise;
const result=await response.json();
if(response.status()!==202) throw Error(JSON.stringify(result));
mkdirSync('../data/audit-skills',{recursive:true});
writeFileSync('../data/audit-skills/run.json',JSON.stringify(result,null,2));
await page.getByText('研究已加入后台队列').waitFor();
await page.screenshot({path:'../docs/design/skills-research-start.png',fullPage:true});
console.log(JSON.stringify({created:result,errors}));
await browser.close();
